name: Build

on: 
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: rust-stm32
    steps:
      - name: Install Protoc
        uses: arduino/setup-protoc@v3

      - name: Install flip-link
        run: cargo install flip-link

      - name: Clone
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build
        run: cargo build --release

      - name: Create binary dist
        run: arm-none-eabi-objcopy -O binary target/thumbv7m-none-eabi/release/rk-meter-agc-pll rk-meter-agc-pll.bin

      - uses: SebRollen/toml-action@v1.2.0
        id: read_version
        with:
          file: 'Cargo.toml'
          field: 'package.version'

      - uses: akkuman/gitea-release-action@v1
        with:
          name: v${{ steps.read_version.outputs.value }}
          body: This is an automatic ${{ steps.read_version.outputs.value }} release!
          prerelease: true
          files: |
            rk-meter-agc-pll.bin
